{
 "title": "Main Dashboard",
 "panels": [
  {
   "title": "Доступность бэкенд-нод",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"node_exporter\"}"
    }
   ]
  },
  {
   "title": "Нагрузка CPU (средняя за 5 мин)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "targets": [
    { "expr": "node_load5" }
   ]
  },
  {
   "title": "HTTP статус-коды (2xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "nginx_vts_server_requests_total{host=\"_\",code=\"2xx\"}"
    }
   ]
  }
 ]
}