all:
  hosts:
    lb1:
      ansible_host: 192.168.100.10
      ansible_user: ansible
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
    lb2:
      ansible_host: 192.168.100.11
      ansible_user: ansible
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
    backend1:
      ansible_host: 192.168.100.20
      ansible_user: ansible
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
    backend2:
      ansible_host: 192.168.100.21
      ansible_user: ansible
      ansible_ssh_private_key_file: /root/.ssh/id_rsa
      ansible_python_interpreter: /usr/bin/python3
    victoriametrics:
      ansible_host: victoriametrics
      ansible_user: root
      ansible_connection: docker
    grafana:
      ansible_host: grafana
      ansible_user: root
      ansible_connection: docker   # можно использовать docker connection, но проще через http API
  children:
    lb:
      hosts:
        lb1:
        lb2:
    backend:
      hosts:
        backend1:
        backend2:
    monitoring:
      hosts:
        grafana:
        victoriametrics:
